timed_reset()
resourseList = [Unlocks.Speed, Unlocks.Expand, Unlocks.Grass]
wheatNum(19)
unlock(Unlocks.Speed)
wheatNum(29)
unlock(Unlocks.Expand)
wheatNum(49)
unlock(Unlocks.Plant)
bushPlanter(False)
bushHarvester(9)
unlock(Unlocks.Speed)
bushHarvester(19)
unlock(Unlocks.Expand)
unlock(Unlocks.Grass)
wheatNum(32)
bushPlanter(True)
bushHarvesterFast(136)
unlock(Unlocks.Carrots)
carrotHarvester(resourseList)
	